#!/bin/bash

./gradlew :incrMinorVersion || exit 1
./gradlew :dockerTagsPush || exit 1

VER=$(./gradlew -q :getCurrentVersion | tail -n 1)
PUBLIC_KEY_PATH=/home/nick/NamelyCoTest.pem

echo "Shopify  pushed with version [$VER] to SANDBOX docker registry"

ssh -i $PUBLIC_KEY_PATH NamelyCoTest.pem ec2-user@ec2-3-123-154-134.eu-central-1.compute.amazonaws.com  "docker service update -d --image 26341/shopify eliftech_shopify_backend"

ssh -i $PUBLIC_KEY_PATH ec2-user@ec2-3-123-154-134.eu-central-1.compute.amazonaws.com  "docker service logs eliftech_shopify_backend -f --since 60s"

