version: '3.4'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
    - 5672:5672
    - 15672:15672
  db:
    image: library/mysql:5.7
    container_name: shopify_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: shopify
      MYSQL_USER: manager
      MYSQL_PASSWORD: manager
      MYSQL_ROOT_PASSWORD: 1234
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    volumes:
      - /opt/eliftech/shopify:/var/lib/mysql